### ISSUE TITLE
Getting error for kubernetes.config.load_incluster_config(). Invalid kube-config file. No configuration found.

### ISSUE THREAD

**Issue by Amithpn** [pypi/warehouse#12391]
**Describe the bug**
I have a microk8s v1.23 running which i have updated from v1.16 latesly. I have a component which list the namespace for installing few components dynamically when there is a request. Below is my code snippet:

```
from kubernetes import client, config

if __name__ == "__main__":
config.load_incluster_config()
namespace = get_namespace()
LOGGER.info("Namespace: "+namespace) 
```

**Expected behavior**
I should not get any exception. Im gettting below error instead:

 ```
kubectl logs -f sagatewaystub-5c84568b-tb8g8
Exception: [Errno 2] No such file or directory: '/app/config/gateway.yaml'
Traceback (most recent call last):
  File "/home/ubuntu/gatewaySoftwareManager.py", line 105, in <module>
    config.load_incluster_config()
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/config/incluster_config.py", line 121, in load_incluster_config
    try_refresh_token=try_refresh_token).load_and_set(client_configuration)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/config/incluster_config.py", line 73, in _load_config
    raise ConfigException("Service token file does not exist.")
kubernetes.config.config_exception.ConfigException: Service token file does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/gatewaySoftwareManager.py", line 107, in <module>
    config.load_kube_config()
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/config/kube_config.py", line 810, in load_kube_config
    persist_config=persist_config)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/config/kube_config.py", line 768, in _get_kube_config_loader
    'Invalid kube-config file. '
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
```

**To Reproduce**

**My Platform**
```
kubectl get node -o wide
NAME     STATUS   ROLES    AGE    VERSION                     INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
devgpu   Ready    <none>   2d1h   v1.23.12-2+7f311b86ce6934   10.142.208.79   <none>        Ubuntu 20.04.5 LTS   5.4.0-128-generic   containerd://1.5.13
devgpu@devgpu:~/go/src/sa-app-operator/sagateway-operator/local_deploy/crds$
```

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
