### ISSUE TITLE
Sunnportal py, I got 410 error after password reset and CONFIG file update

### ISSUE THREAD

**Issue by GreeneumNetwork** [pypi/warehouse#12857]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by GreeneumNetwork** [comment]
2023-01-18 12:04:33,221 DEBUG: GET /services/authentication/100/shelegyael%40gmail.com?password=<password>
Traceback (most recent call last):
  File "sunnyportal2file", line 484, in <module>
    main()
  File "sunnyportal2file", line 436, in main
    for plant in client.get_plants():
  File "/home/greeneum/Greeneum/sunnyportal/client.py", line 62, in get_plants
    req = requests.PlantListRequest(self.get_token())
  File "/home/greeneum/Greeneum/sunnyportal/client.py", line 51, in get_token
    self.token = self.do_request(req)
  File "/home/greeneum/Greeneum/sunnyportal/client.py", line 46, in do_request
    return request.perform(conn)
  File "/home/greeneum/Greeneum/sunnyportal/requests.py", line 77, in perform
    raise RuntimeError(
RuntimeError: HTTP error performing authentication request: 410 Gone

**Comment by miketheman** [comment]
Hi, this issue tracker is for issues with the codebase behind [pypi.org](https://pypi.org/) itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
