### ISSUE TITLE
PPDF2 TABLE creation fails with some fonts

### ISSUE THREAD

**Issue by aeris07** [pypi/warehouse#13354]
I got below error when I want to create a table with the following code and font:
using FPDF2 version 2.7.1

**CODE**:

pdf = FPDF()
pdf.add_page()
pdf.add_font('Tr-arial', '', "TR Arial.ttf", uni=True)
#pdf.set_font("Times", size=10)

pdf.set_font("Tr-Arial", size=16)
with pdf.table() as table:
    for data_row in TABLE_DATA:
        row = table.row()
        for datum in data_row:
            row.cell(datum)
pdf.output('table.pdf')

**ERROR:**
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 18, in <module>
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\PC\PycharmProjects\pythonProject\venv\Lib\site-packages\fpdf\fpdf.py", line 4716, in table
    table.render()
  File "C:\Users\PC\PycharmProjects\pythonProject\venv\Lib\site-packages\fpdf\table.py", line 98, in render
    with self._fpdf.offset_rendering() as test:
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\PC\PycharmProjects\pythonProject\venv\Lib\site-packages\fpdf\fpdf.py", line 4522, in offset_rendering
    recorder = FPDFRecorder(self, accept_page_break=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\PycharmProjects\pythonProject\venv\Lib\site-packages\fpdf\recorder.py", line 29, in __init__
    self._initial = deepcopy(self.pdf.__dict__)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'dict_keys' object"

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
