### ISSUE TITLE
Circular import for warehouse.oidc

### ISSUE THREAD

**Issue by miketheman** [pypi/warehouse#13498]
Surfaced via:

```shellsession
python -c "import warehouse.oidc"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "workpath/warehouse/warehouse/oidc/__init__.py", line 13, in <module>
    from warehouse.oidc.interfaces import IOIDCPublisherService
  File "workpath/warehouse/warehouse/oidc/interfaces.py", line 19, in <module>
    from warehouse.packaging.models import Project
  File "workpath/warehouse/warehouse/packaging/__init__.py", line 17, in <module>
    from warehouse.accounts.models import Email, User
  File "workpath/warehouse/warehouse/accounts/__init__.py", line 22, in <module>
    from warehouse.accounts.security_policy import (
  File "workpath/warehouse/warehouse/accounts/security_policy.py", line 36, in <module>
    from warehouse.utils.security_policy import AuthenticationMethod
  File "workpath/warehouse/warehouse/utils/security_policy.py", line 21, in <module>
    from warehouse.oidc.models import OIDCPublisher
  File "workpath/warehouse/warehouse/oidc/models.py", line 24, in <module>
    from warehouse.oidc.interfaces import SignedClaims
ImportError: cannot import name 'SignedClaims' from partially initialized module 'warehouse.oidc.interfaces' (most likely due to a circular import) (workpath/warehouse/warehouse/oidc/interfaces.py)
```

This isn't posing a problem in production (yet). I found it when I tried to filter out the warnings from `InsecureOIDCPublisherWarning` - but we should figure out how to not have a circular import.

**Comment by woodruffw** [comment]
Working on this now!
