### ISSUE TITLE
opencv-python has a dependency on numpy >= 1.17, while apparently requiring a higher version

### ISSUE THREAD

**Issue by gsabdiv** [pypi/warehouse#14728]
**Describe the bug**
The wheel for opencv_python-4.8.1.76 and opencv_python-4.8.1.78 (haven't tried other ones) have a dependency on numpy>=1.17.0, but apparently need a more recent version.

**Expected behavior**
Have a dependency on the numpy version that really is required.

**To Reproduce**
pip download opencv-python
I got opencv_python-4.8.1.78-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.
pip install ./opencv_python-4.8.1.78-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, it says:
Requirement already satisfied: numpy>=1.17.0

>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/censored/.local/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/censored/.local/lib/python3.9/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/censored/.local/lib/python3.9/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/appl/std/python/linuxIntel64/3.9.2/gcc/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/censored/.local/lib/python3.9/site-packages/cv2/typing/__init__.py", line 69, in <module>
    NumPyArrayGeneric = numpy.ndarray[typing.Any, numpy.dtype[numpy.generic]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable

**My Platform**
python 3.9.2 on AlmaLinux 8, x64

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
