### ISSUE TITLE
p5 Installation error: metadata-generation-failed

### ISSUE THREAD

**Issue by BobWeerts** [pypi/warehouse#14996]
**Describe the bug**
 Installing p5 throws a metadata-generation-failed error

**Expected behavior**
 P5 should install properly

**To Reproduce**
 pip install p5 --user and/or pip3 install p5 --user

**My Platform**
* Mac Sonoma 14.1.1
* Python version 3.9.6

**Additional context**
Terminal messages:

Collecting p5 Using cached p5-0.8.3-py3-none-any.whl.metadata (4.5 kB) Collecting freetype-py==2.1.0.post1 (from p5) Using cached freetype_py-2.1.0.post1-py2.py3-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (1.6 MB) Collecting glfw>=2.5.9 (from p5) Using cached glfw-2.6.3-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-macosx_10_6_intel.whl.metadata (5.4 kB) Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from p5) (1.26.1) Collecting Pillow==9.0.1 (from p5) Using cached Pillow-9.0.1.tar.gz (49.5 MB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done Collecting vispy==0.10.0 (from p5) Using cached vispy-0.10.0.tar.gz (2.4 MB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done Collecting PyOpenGL-accelerate==3.1.7 (from p5) Using cached PyOpenGL-accelerate-3.1.7.tar.gz (562 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Installing backend dependencies ... done Preparing metadata (pyproject.toml) ... done Collecting PyOpenGL==3.1.6 (from p5) Using cached PyOpenGL-3.1.6-py3-none-any.whl (2.4 MB) Collecting requests>=2.25.0 (from p5) Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB) INFO: pip is looking at multiple versions of p5 to determine which version is compatible with other requirements. This could take a while. Collecting p5 Using cached p5-0.8.2-py3-none-any.whl (144 kB) Collecting glfw==1.11.2 (from p5) Using cached glfw-1.11.2-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-macosx_10_6_intel.whl (99 kB) Collecting PyOpenGL-accelerate==3.1.6 (from p5) Using cached PyOpenGL-accelerate-3.1.6.tar.gz (550 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done Collecting p5 Using cached p5-0.8.1-py3-none-any.whl (144 kB) Using cached p5-0.8.0-py3-none-any.whl (136 kB) Collecting numpy==1.18.5 (from p5) Using cached numpy-1.18.5.zip (5.4 MB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error
× Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [56 lines of output] Running from numpy source directory. :461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates /private/var/folders/gp/2ws1vxmj4kzc6w665ng0c7pr0000gn/T/pip-install-kyh2gb1k/numpy_cd3c819e131a47ec9576754238b9dca7/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. required_version = LooseVersion('0.29.14') /private/var/folders/gp/2ws1vxmj4kzc6w665ng0c7pr0000gn/T/pip-install-kyh2gb1k/numpy_cd3c819e131a47ec9576754238b9dca7/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. if LooseVersion(cython_version) < required_version:
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
              self.rng_state.ctr.v[i] = counter[i]
  
          self._reset_state_variables()
  
          self._bitgen.state = <void *>&self.rng_state
          self._bitgen.next_uint64 = &philox_uint64
                                     ^
  ------------------------------------------------------------
  
  _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_philox.pyx
  Traceback (most recent call last):
    File "/private/var/folders/gp/2ws1vxmj4kzc6w665ng0c7pr0000gn/T/pip-install-kyh2gb1k/numpy_cd3c819e131a47ec9576754238b9dca7/tools/cythonize.py", line 238, in <module>
      main()
    File "/private/var/folders/gp/2ws1vxmj4kzc6w665ng0c7pr0000gn/T/pip-install-kyh2gb1k/numpy_cd3c819e131a47ec9576754238b9dca7/tools/cythonize.py", line 234, in main
      find_process_files(root_dir)
    File "/private/var/folders/gp/2ws1vxmj4kzc6w665ng0c7pr0000gn/T/pip-install-kyh2gb1k/numpy_cd3c819e131a47ec9576754238b9dca7/tools/cythonize.py", line 225, in find_process_files
      process(root_dir, fromfile, tofile, function, hash_db)
    File "/private/var/folders/gp/2ws1vxmj4kzc6w665ng0c7pr0000gn/T/pip-install-kyh2gb1k/numpy_cd3c819e131a47ec9576754238b9dca7/tools/cythonize.py", line 191, in process
      processor_function(fromfile, tofile)
    File "/private/var/folders/gp/2ws1vxmj4kzc6w665ng0c7pr0000gn/T/pip-install-kyh2gb1k/numpy_cd3c819e131a47ec9576754238b9dca7/tools/cythonize.py", line 80, in process_pyx
      subprocess.check_call(
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
  Cythonizing sources
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/gp/2ws1vxmj4kzc6w665ng0c7pr0000gn/T/pip-build-env-bb81ehkb/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/private/var/folders/gp/2ws1vxmj4kzc6w665ng0c7pr0000gn/T/pip-build-env-bb81ehkb/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "/private/var/folders/gp/2ws1vxmj4kzc6w665ng0c7pr0000gn/T/pip-build-env-bb81ehkb/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 488, in <module>
    File "<string>", line 469, in setup_package
    File "<string>", line 275, in generate_cython
  RuntimeError: Running cythonize failed!
  [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
× Encountered error while generating package metadata. ╰─> See above for output.
note: This is an issue with the package mentioned above, not pip. hint: See above for details. bobweerts@Bobs-iMac ~ %

**Comment by miketheman** [comment]
Hi, this issue tracker is for issues with the codebase behind [pypi.org](https://pypi.org/) itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
