### ISSUE TITLE
xterm is not available in the registry anymore

### ISSUE THREAD

**Issue by 0berstmarschall** [pypi/warehouse#16049]
Hello,

I have an issue with installation of https://pypi.org/project/xterm/ . It looks like this package was removed from the registry.
https://pypi.org/project/xterm/ returns 404 http code.
Installation error:
`ERROR: No matching distribution found for xterm`

**Description**
Here is my verbose output of `pip install`

```
root@05242cb72e46:/# pip install -v xterm
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-adhyree0
Created temporary directory: /tmp/pip-req-tracker-yv99mktp
Initialized build tracking at /tmp/pip-req-tracker-yv99mktp
Created build tracker: /tmp/pip-req-tracker-yv99mktp
Entered build tracker: /tmp/pip-req-tracker-yv99mktp
Created temporary directory: /tmp/pip-install-v84nhy1y
1 location(s) to search for versions of xterm:
* https://pypi.org/simple/xterm/
Fetching project page and analyzing links: https://pypi.org/simple/xterm/
Getting page https://pypi.org/simple/xterm/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/xterm/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/xterm/ HTTP/1.1" 404 13
Status code 404 not in (200, 203, 300, 301)
Could not fetch URL https://pypi.org/simple/xterm/: 404 Client Error: Not Found for url: https://pypi.org/simple/xterm/ - skipping
Given no hashes to check 0 links for project 'xterm': discarding no candidates
ERROR: Could not find a version that satisfies the requirement xterm (from versions: none)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-yv99mktp'
ERROR: No matching distribution found for xterm
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 926, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for xterm
```

**Expected behavior**
xterm is available and can be installed.

**To Reproduce**
pip install -v xterm

**My Platform**
Ubuntu 20.04
pip 20.0.2

**Comment by miketheman** [comment]
The `xterm` package was removed from the registry by the owner of the package.

The index response is accurate, and thus not a bug.

You likely want to explore other venues for this code.
